//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicFront.SpecialtyReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialtyContract", Namespace="http://schemas.datacontract.org/2004/07/SampleDataContracts")]
    [System.SerializableAttribute()]
    public partial class SpecialtyContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string despField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desp {
            get {
                return this.despField;
            }
            set {
                if ((object.ReferenceEquals(this.despField, value) != true)) {
                    this.despField = value;
                    this.RaisePropertyChanged("desp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpecialtyReference.ISpecialtyService")]
    public interface ISpecialtyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpecialtyService/getSpecialtyData", ReplyAction="http://tempuri.org/ISpecialtyService/getSpecialtyDataResponse")]
        ClinicFront.SpecialtyReference.SpecialtyContract getSpecialtyData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpecialtyService/getSpecialtyData", ReplyAction="http://tempuri.org/ISpecialtyService/getSpecialtyDataResponse")]
        System.Threading.Tasks.Task<ClinicFront.SpecialtyReference.SpecialtyContract> getSpecialtyDataAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpecialtyService/getAllSpecialty", ReplyAction="http://tempuri.org/ISpecialtyService/getAllSpecialtyResponse")]
        System.Collections.Generic.List<ClinicFront.SpecialtyReference.SpecialtyContract> getAllSpecialty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpecialtyService/getAllSpecialty", ReplyAction="http://tempuri.org/ISpecialtyService/getAllSpecialtyResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClinicFront.SpecialtyReference.SpecialtyContract>> getAllSpecialtyAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpecialtyServiceChannel : ClinicFront.SpecialtyReference.ISpecialtyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpecialtyServiceClient : System.ServiceModel.ClientBase<ClinicFront.SpecialtyReference.ISpecialtyService>, ClinicFront.SpecialtyReference.ISpecialtyService {
        
        public SpecialtyServiceClient() {
        }
        
        public SpecialtyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpecialtyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpecialtyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpecialtyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClinicFront.SpecialtyReference.SpecialtyContract getSpecialtyData(string id) {
            return base.Channel.getSpecialtyData(id);
        }
        
        public System.Threading.Tasks.Task<ClinicFront.SpecialtyReference.SpecialtyContract> getSpecialtyDataAsync(string id) {
            return base.Channel.getSpecialtyDataAsync(id);
        }
        
        public System.Collections.Generic.List<ClinicFront.SpecialtyReference.SpecialtyContract> getAllSpecialty() {
            return base.Channel.getAllSpecialty();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClinicFront.SpecialtyReference.SpecialtyContract>> getAllSpecialtyAsync() {
            return base.Channel.getAllSpecialtyAsync();
        }
    }
}
