//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicFront.TypeReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeContract", Namespace="http://schemas.datacontract.org/2004/07/SampleDataContracts")]
    [System.SerializableAttribute()]
    public partial class TypeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string despField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desp {
            get {
                return this.despField;
            }
            set {
                if ((object.ReferenceEquals(this.despField, value) != true)) {
                    this.despField = value;
                    this.RaisePropertyChanged("desp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TypeReference.ITypeService")]
    public interface ITypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeService/getTypetData", ReplyAction="http://tempuri.org/ITypeService/getTypetDataResponse")]
        ClinicFront.TypeReference.TypeContract getTypetData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeService/getTypetData", ReplyAction="http://tempuri.org/ITypeService/getTypetDataResponse")]
        System.Threading.Tasks.Task<ClinicFront.TypeReference.TypeContract> getTypetDataAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeService/getTypeList", ReplyAction="http://tempuri.org/ITypeService/getTypeListResponse")]
        ClinicFront.TypeReference.TypeContract[] getTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeService/getTypeList", ReplyAction="http://tempuri.org/ITypeService/getTypeListResponse")]
        System.Threading.Tasks.Task<ClinicFront.TypeReference.TypeContract[]> getTypeListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITypeServiceChannel : ClinicFront.TypeReference.ITypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TypeServiceClient : System.ServiceModel.ClientBase<ClinicFront.TypeReference.ITypeService>, ClinicFront.TypeReference.ITypeService {
        
        public TypeServiceClient() {
        }
        
        public TypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClinicFront.TypeReference.TypeContract getTypetData(string id) {
            return base.Channel.getTypetData(id);
        }
        
        public System.Threading.Tasks.Task<ClinicFront.TypeReference.TypeContract> getTypetDataAsync(string id) {
            return base.Channel.getTypetDataAsync(id);
        }
        
        public ClinicFront.TypeReference.TypeContract[] getTypeList() {
            return base.Channel.getTypeList();
        }
        
        public System.Threading.Tasks.Task<ClinicFront.TypeReference.TypeContract[]> getTypeListAsync() {
            return base.Channel.getTypeListAsync();
        }
    }
}
