//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicFront.DurationReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DurationContract", Namespace="http://schemas.datacontract.org/2004/07/SampleDataContracts")]
    [System.SerializableAttribute()]
    public partial class DurationContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string despField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desp {
            get {
                return this.despField;
            }
            set {
                if ((object.ReferenceEquals(this.despField, value) != true)) {
                    this.despField = value;
                    this.RaisePropertyChanged("desp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DurationReference.IDurationService")]
    public interface IDurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDurationService/getDurationList", ReplyAction="http://tempuri.org/IDurationService/getDurationListResponse")]
        System.Collections.Generic.List<ClinicFront.DurationReference.DurationContract> getDurationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDurationService/getDurationList", ReplyAction="http://tempuri.org/IDurationService/getDurationListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClinicFront.DurationReference.DurationContract>> getDurationListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDurationService/GetDurationData", ReplyAction="http://tempuri.org/IDurationService/GetDurationDataResponse")]
        ClinicFront.DurationReference.DurationContract GetDurationData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDurationService/GetDurationData", ReplyAction="http://tempuri.org/IDurationService/GetDurationDataResponse")]
        System.Threading.Tasks.Task<ClinicFront.DurationReference.DurationContract> GetDurationDataAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDurationServiceChannel : ClinicFront.DurationReference.IDurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DurationServiceClient : System.ServiceModel.ClientBase<ClinicFront.DurationReference.IDurationService>, ClinicFront.DurationReference.IDurationService {
        
        public DurationServiceClient() {
        }
        
        public DurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ClinicFront.DurationReference.DurationContract> getDurationList() {
            return base.Channel.getDurationList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClinicFront.DurationReference.DurationContract>> getDurationListAsync() {
            return base.Channel.getDurationListAsync();
        }
        
        public ClinicFront.DurationReference.DurationContract GetDurationData(string id) {
            return base.Channel.GetDurationData(id);
        }
        
        public System.Threading.Tasks.Task<ClinicFront.DurationReference.DurationContract> GetDurationDataAsync(string id) {
            return base.Channel.GetDurationDataAsync(id);
        }
    }
}
