//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicFront.UrgentReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrgentContract", Namespace="http://schemas.datacontract.org/2004/07/SampleDataContracts")]
    [System.SerializableAttribute()]
    public partial class UrgentContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string despField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desp {
            get {
                return this.despField;
            }
            set {
                if ((object.ReferenceEquals(this.despField, value) != true)) {
                    this.despField = value;
                    this.RaisePropertyChanged("desp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UrgentReference.IUrgentService")]
    public interface IUrgentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrgentService/getUrgentData", ReplyAction="http://tempuri.org/IUrgentService/getUrgentDataResponse")]
        ClinicFront.UrgentReference.UrgentContract getUrgentData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrgentService/getUrgentData", ReplyAction="http://tempuri.org/IUrgentService/getUrgentDataResponse")]
        System.Threading.Tasks.Task<ClinicFront.UrgentReference.UrgentContract> getUrgentDataAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrgentService/getCodeList", ReplyAction="http://tempuri.org/IUrgentService/getCodeListResponse")]
        ClinicFront.UrgentReference.UrgentContract[] getCodeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrgentService/getCodeList", ReplyAction="http://tempuri.org/IUrgentService/getCodeListResponse")]
        System.Threading.Tasks.Task<ClinicFront.UrgentReference.UrgentContract[]> getCodeListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUrgentServiceChannel : ClinicFront.UrgentReference.IUrgentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrgentServiceClient : System.ServiceModel.ClientBase<ClinicFront.UrgentReference.IUrgentService>, ClinicFront.UrgentReference.IUrgentService {
        
        public UrgentServiceClient() {
        }
        
        public UrgentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrgentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrgentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrgentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClinicFront.UrgentReference.UrgentContract getUrgentData(string id) {
            return base.Channel.getUrgentData(id);
        }
        
        public System.Threading.Tasks.Task<ClinicFront.UrgentReference.UrgentContract> getUrgentDataAsync(string id) {
            return base.Channel.getUrgentDataAsync(id);
        }
        
        public ClinicFront.UrgentReference.UrgentContract[] getCodeList() {
            return base.Channel.getCodeList();
        }
        
        public System.Threading.Tasks.Task<ClinicFront.UrgentReference.UrgentContract[]> getCodeListAsync() {
            return base.Channel.getCodeListAsync();
        }
    }
}
